baseurl = "http://dronesoc.co.uk/"
languageCode = "en-gb"
title = "University of York Drone Society | DroneSoc"
theme = "hugo-lithium-theme"

[permalinks]
    post = "/:year/:month/:day/:title/"
    committee = "/:title/"
    resources = "/:title/"
    membership = "/:title/"

[[menu.main]]
    name = "Committee"
    url = "/committee/"
[[menu.main]]
    name = "Events"
    url = ""
[[menu.main]]
    name = "Resources"
    url = "/resources/"
[[menu.main]]
    name = "Membership"
    url = "/membership/"

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50

